### ISSUE TITLE
Error when trying to open Crown Falls island to Anno Designer

### ISSUE THREAD

**Issue by DerRiegel** [NiHoel/Anno1800SavegameVisualizer#2]
Hi DuxVitae,

I get the following error when trying to open Crown Falls to the Anno Designer on any savegame, works fine for all other islands. Seems strange why Crown Falls would have no rectangle array. Maybe this has to do with Crown Falls being located in the top corner of the map?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~\Downloads\Anno 1800\Anno1800SavegameVisualizerv2.0\tools\savegame_visualizer_gui.py:484, in VisualizerGUI.compose_body.<locals>.callback_save(btn)
    483 def callback_save(btn):
--> 484     self.open_in_ad()

File ~\Downloads\Anno 1800\Anno1800SavegameVisualizerv2.0\tools\savegame_visualizer_gui.py:858, in VisualizerGUI.open_in_ad(self)
    856 options = self.get_options()
    857 print("options = " + str(options))
--> 858 ad_config = island.get_layout(options=options)
    859 ad_json = json.dumps(ad_config)
    860 path = self.get_path(ad_json)

File ~\Downloads\Anno 1800\Anno1800SavegameVisualizerv2.0\tools\a7s_model.py:3981, in Island.get_layout(self, options)
   3978 if b.guid == 117741:  # Enbesa river slot
   3979     continue
-> 3981 obj = b.generate_ad_object()
   3983 if obj is None:
   3984     continue

File ~\Downloads\Anno 1800\Anno1800SavegameVisualizerv2.0\tools\a7s_model.py:4409, in Building.generate_ad_object(self)
   4406 rot = rot % 4
   4407 obj["Direction"] = A7PARAMS["directions"][rot]
-> 4409 pos = self.get_relative_position()
   4410 obj["Size"] = "{},{}".format(self.rotated_size[0], self.rotated_size[1])
   4411 obj["Position"] = "{},{}".format(pos[0], pos[1])

File ~\Downloads\Anno 1800\Anno1800SavegameVisualizerv2.0\tools\a7s_model.py:4380, in Building.get_relative_position(self)
   4373 def get_relative_position(self):
   4374     """
   4375     Returns the integer 2D coordinates of the northern corenr of the bounding box
   4376     relative to the northern edge of the island
   4377     Uses the same coordinate system as the size attribute
   4378     """
-> 4380     tl = self.island.rectangle[1]
   4381     if self.bounding_rectangle is None:
   4382         return np.array([int(tl[1] - round(self.position[2] + self.rotated_size[0] / 2)),
   4383                          int(tl[0] - round(self.position[0] + self.rotated_size[1] / 2))])

AttributeError: 'Island' object has no attribute 'rectangle'

**Comment by NiHoel** [comment]
Do you use any mods?
Can you send me the savegame?

**Comment by DerRiegel** [comment]
Don't use any mods.

I tried this on one of my own savegames as well as a Rekordbau Savegame from ehebdib posted on Fox's Discord, can be downloaded from here https://easyupload.io/b0j9gy

**Comment by NiHoel** [comment]
Fixed in v2.1

Islands from the first DLC were missing.
