### ISSUE TITLE
JupyterLabs can't find the save file

### ISSUE THREAD

**Issue by auddie2015** [NiHoel/Anno1800SavegameVisualizer#4]
Unpacking ...
ERROR: [WinError 2] The system cannot find the file specified

It ran fine the last time I played. The only thing that has changed between then and now is JupyterLab had an update. I tried copying the save to a different folder in case my antivirus decided to not let the software ready My Documents. I tried putting an exception into the antivirus. I tried putting the save into the root folder of a completely separate hard drive. The results are the same regardless of where I try to access the file. 

EDIT: I have to use CTRL-V to paste the save location as the right click menu does not have paste. I am not sure if this is the cause because the log file doesn't specify.

**Comment by auddie2015** [comment]
I am not sure if this is the cause or not but here is what I have found. Avast thinks Python has a virus in it and it blocks it from running, even with an exclusion. Even with Avast disabled, the file is not found. I can't tell if this is related to each other or not. This all worked fine Friday. I have been using the design map I made then to plan expansions.

**Comment by NiHoel** [comment]
Have you tried re-installing the older version of Jupyter Lab and followed the uninstall instruction?
https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#uninstalling-jupyterlab-desktop

**Comment by auddie2015** [comment]
I followed the instructions to remove the update and reinstall the previous version. Avast was still having an issue so I contacted them about the issue. I don't think the problem is with your code so I need to switch the issue to JupyterLab. 

For information, if I use the proper file name, I get the error I reported.
ERROR: [WinError 2] The system cannot find the file specified. 

If I misspell the name, I get a completely different error.
ERROR: File or path do not exist: X:\Libraries\Documents\Anno 1800\...

I am not good with this stuff so I have no idea why there would be different errors.

**Comment by auddie2015** [comment]
I got it to work, if unconventionally. I installed my own Anaconda-Python, set the environment to it, and it worked. Like I said 7 hours ago before my crash course in python environments, it wasn't your code but your reply let me to the answer. thanks!
